server:
  port: 8081
resources:
    static-locations:
      classpath: /static/,classpath:/views
spring:
  thymeleaf:
    prefix=classpath:/static/:
  datasource:
    username: root
    url: jdbc:mysql://127.0.0.1:3306/mams-common?useUnicode=true&characterEncoding=utf8&serverTimezone=GMT
    password: tcp666
